### ISSUE TITLE
odcore::strings::StringToolbox::split

### ISSUE THREAD

**Issue by olbender** [se-research/OpenDaVINCI#108]
The following gives an empty vector:
std::vector<std::string> array = odcore::strings::StringToolbox::split("foobar", ',');

rather than the expected vector containing the single element "foobar", which would for example be given by 'split' in Pyton, Javascript, and Bash.

Can this be changed?

**Comment by chrberger** [comment]
Fixed with https://github.com/se-research/OpenDaVINCI/commit/1c204b3a79df6b4242e5b947c6cea886bfbdb958
