### ISSUE TITLE
Compiler warning about odcore/base/Arguments

### ISSUE THREAD

**Issue by chrberger** [se-research/OpenDaVINCI#123]
Hi @crispin-kirchner, the compiler complains about this class:

[  2%] Building CXX object CMakeFiles/opendavinci-core.dir/src/odcore/base/Arguments.cpp.o
In file included from /home/odv/GITHUB/OpenDaVINCI/libopendavinci/src/odcore/base/Arguments.cpp:3:0:
/home/odv/GITHUB/OpenDaVINCI/libopendavinci/include/opendavinci/odcore/base/Arguments.h:20:15: warning: ‘class odcore::base::Arguments’ has pointer data members [-Weffc++]
         class Arguments {
               ^
/home/odv/GITHUB/OpenDaVINCI/libopendavinci/include/opendavinci/odcore/base/Arguments.h:20:15: warning:   but does not override ‘odcore::base::Arguments(const odcore::base::Arguments&)’ [-Weffc++]
/home/odv/GITHUB/OpenDaVINCI/libopendavinci/include/opendavinci/odcore/base/Arguments.h:20:15: warning:   or ‘operator=(const odcore::base::Arguments&)’ [-Weffc++]
/home/odv/GITHUB/OpenDaVINCI/libopendavinci/src/odcore/base/Arguments.cpp: In constructor ‘odcore::base::Arguments::Arguments(const std::initializer_list<std::__cxx11::basic_string<char> >&)’:
/home/odv/GITHUB/OpenDaVINCI/libopendavinci/src/odcore/base/Arguments.cpp:8:9: warning: ‘odcore::base::Arguments::argvValues_’ should be initialized in the member initialization list [-Weffc++]
         Arguments::Arguments(const std::initializer_list<std::string> & argList)

Could you please fix this warning? Thanks.

**Comment by chrberger** [comment]
@crispin-kirchner Did we fix this issue?

**Comment by crispin-kirchner** [comment]
No, I deemed other matters as more urgent. The fix should not take long, I guess I will just fix this during the Monday session.

**Comment by chrberger** [comment]
@crispin-kirchner Would it be possible to provide a quick fix before our next testing session mid-January?

**Comment by chrberger** [comment]
@crispin-kirchner: May I ask you to provide a fix so that we can close this issue? Thanks

**Comment by crispin-kirchner** [comment]
Thank you for the reminder, I will fix this after handing in the thesis (on 23.02.17)

**Comment by crispin-kirchner** [comment]
I made an according pull request: #166
