### ISSUE TITLE
Replay recordings with .H264 files

### ISSUE THREAD

**Issue by HangYin2015** [se-research/OpenDaVINCI#182]
When a recording containing .H264 files is made with odrecorderh264, it can be replayed using odcockpit. Currently, odcockpit requires that each .H264 file should not be renamed. Otherwise, odcockpit will crash.

**Comment by chrberger** [comment]
Fixed with https://github.com/se-research/OpenDaVINCI/commit/cffb2dee4b668f89074657564ea859324cc4a5e1
