### ISSUE TITLE
compile using sudo

### ISSUE THREAD

**Issue by bellonemauro** [se-research/OpenDaVINCI#20]
Hello Christian, 
I have tried to compile the library just today (on Ubuntu 14.04), and due to some automatic install package into the building tree of opendavici, the only way to build was to use "sudo" which is not the best way. 
Mauro

**Comment by chrberger** [comment]
Hi Mauro,

CMake's default installation target would be located at /usr where you need superuser rights to write to.

Thus, setting CMake's parameter CMAKE_INSTALL_PREFIX to a directory where your user has write permission is solving your question.

Best regards,

   Christian

**Comment by bellonemauro** [comment]
works ! thanks !
