### ISSUE TITLE
Fix python dependecy for modern sytems.

### ISSUE THREAD

**Issue by donkahlero** [se-research/OpenDaVINCI#23]
Due to the fact that a lot of modern distros are using python3 as their default python their symlink /usr/bin/python points to /usr/bin/python3

Overrwriting this by sudo ln -sf /usr/bin/python2.7 /usr/bin/python is a bit nasty.

Is it possible to change the dependecy to the 2.7 binary instead to the symlink?

**Comment by donkahlero** [comment]
If I have time I will check out this issue myself. Just let you know.

**Comment by chrberger** [comment]
The reason for Python 2.7 is that CxxTest cannot cope with the newer interpreter. You can have a look at the following command line parameter:

-DPYTHON_EXECUTABLE:FILEPATH=/path/to/python2.7

Another simple workaround would be to create a bin folder in your $HOME folder and set the symlink to python2.7 there; then, let cmake use that bin folder during the configuration process:

$ mkdir $HOME/bin
$ ln -sf /path/to/python2.7 $HOME/bin/python
$ PATH=$HOME/bin:$PATH cmake <your cmake options>

**Comment by donkahlero** [comment]
My point is not that it is not working with the symlink created.
The point is more that other packages depending on the default python on Arch do not work anymore because /etc/bin/python does now point to v2.7.

**Comment by chrberger** [comment]
v2.4.8 is solving this as well
