### ISSUE TITLE
autp_ptr -> unique_ptr ?

### ISSUE THREAD

**Issue by daixtrose** [se-research/OpenDaVINCI#28]
According to many internet sources, `auto_ptr` is deprecated and `unique_ptr` [c|sh]ould be used instead, see e.g.  [n1856](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2005/n1856.html#20.4.5%20-%20Class%20template%20auto_ptr). 

Yet the coding guidelines of OpneDaVINCI require `auto_ptr`. Are there plans to change this in the future?

**Comment by chrberger** [comment]
The observation regarding auto_ptr and unique_ptr is valid. The coding guidelines refer solely to the use of wrapped pointers in local scopes to achieve automated resource management.
