### ISSUE TITLE
Issues while implementing "TimeTriggeredExample" tutorial

### ISSUE THREAD

**Issue by phmasek** [se-research/OpenDaVINCI#38]
I'm getting compiling errors while trying to implement the bare minimum of the code presented in: [link](http://opendavinci.readthedocs.org/en/latest/tutorials.html#time-triggered-sender)

All libraries are updated.

![image](https://cloud.githubusercontent.com/assets/1712993/13390863/4445d6e4-ded1-11e5-8b29-0466ccaa9f0d.png)

**Comment by Pletron** [comment]
Might have found the issue. Could be un-updated libraries. Rebuilding now and will test it again.

**Comment by Pletron** [comment]
Still the same problem after rebuilding with updated libraries.

**Comment by phmasek** [comment]
Works with `-std=c++0x` flag while compiling. As `-std=c++0x` compiles with C++11 compiler.

```
g++ -I /opt/od3/include -c -std=c++0x TimeTriggerExample.cpp -o TimeTriggerExample.o
g++ -o timetriggerexample TimeTriggerExample.o -lopendavinci -lpthread
```
